### PR TITLE
Basic Report Structure

### PR DESCRIPTION
**Pull request by Silvertrousers**
Adding a basic report structure based on last year's report. Chapters are labeled 000 to 015. Each of the agent teams has its own chapter, so do the front end and back end. A great deal of these can be written up now or very soon.

We will need to start focusing on experimental design very soon.

### CODE REVIEW

**Review by jzzheng22 — CHANGES_REQUESTED** [review]
Team 6 file is currently empty, can you add a chapter line there?

**Comment by jzzheng22** [comment]
You'll have to edit https://github.com/SOMAS2021/SOMAS-Final-Report/blob/main/main.tex as well

**Comment by JaafarRammal** [comment]
FYI pipeline failure cause: https://github.com/SOMAS2021/SOMAS-Final-Report/runs/4651533461?check_suite_focus=true#step:4:259

**Comment by Silvertrousers** [comment]
Changes have been made and it compiles, can you guys re-review this

**Review by jzzheng22 — APPROVED** [review]

**Pull request merged**
